[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120

[tool.mypy]
mypy_path="./src"
# The following options are set by the --strict command line flag
warn_unused_configs=true
disallow_any_generics=true
disallow_subclassing_any=true
# disallow_untyped_calls=true
disallow_untyped_defs=true
disallow_incomplete_defs=true
check_untyped_defs=true
disallow_untyped_decorators=true
no_implicit_optional=true
warn_redundant_casts=true
warn_unused_ignores=true
warn_return_any=true
# no_implicit_reexport=true
strict_equality=true
# End of --strict options
ignore_missing_imports=true
show_error_codes=true
plugins="numpy.typing.mypy_plugin"

[tool.pylint.'MESSAGES CONTROL']
disable = "too-few-public-methods, missing-docstring, logging-fstring-interpolation, enable=useless-suppression"

[tool.pylint.FORMAT]
max-line-length=120

[tool.pylint.SIMILARITIES]
ignore-comments="no"

[tool.pylint.MISCELLANEOUS]
notes="FIXME,XXX"

[tool.pylint.BASIC]
argument-rgx='(([a-z][a-z0-9_]{0,40})|(_[a-z0-9_]*))$'
class-rgx='[A-Z_][a-zA-Z0-9]*$'
variable-rgx='(([a-z][a-z0-9_]{0,40})|(_[a-z0-9_]*))$'

[tool.pylint.CLASSES]
defining-attr-methods="__init__, __new__, setUp, __enter__"
valid-metaclass-classmethod-first-arg="mcs"

[tool.pylint.DESIGN]
max-attributes=16
max-parents=15

[tool.pylint.EXCEPTIONS]
overgeneral-exceptions="BaseException"
